#!/usr/bin/env bash
# Regenerate the observatory SPICE kernels from observatories.defs.
#
# spice_kernels/ and ./pinpoint are gitignored (binary kernels + NAIF tool),
# so observatories.defs is the tracked source of truth for the ground
# stations. Run this after editing observatories.defs (e.g. adding a station)
# to rebuild:
#   spice_kernels/observatories.bsp   station ephemerides (SPK)
#   spice_kernels/observatories.tf    name->code map + topocentric frames (FK)
#   spice_kernels/observatory_radii.tpc  hand-maintained radii for edterm()
#
# observatory_radii.tpc is NOT produced by PINPOINT (it would be dropped on
# regeneration); it is (re)written here and loaded after observatories.tf so
# its radii take precedence. Stations: DWINGELOO 399999, STOCKERT 399998,
# ATA 399997.
#
# Requires ./pinpoint (NAIF PINPOINT 3.3.0) in this directory.
set -euo pipefail
cd "$(dirname "$0")"

KDIR=spice_kernels
PINPOINT=./pinpoint

[ -x "$PINPOINT" ] || { echo "ERROR: $PINPOINT not found/executable"; exit 1; }

# PINPOINT refuses to overwrite; clear the prior outputs first.
rm -f "$KDIR/observatories.bsp" "$KDIR/observatories.tf"
"$PINPOINT" -def observatories.defs \
            -pck "$KDIR/pck00011.tpc" \
            -spk "$KDIR/observatories.bsp" \
            -fk  "$KDIR/observatories.tf"

cat > "$KDIR/observatory_radii.tpc" <<'TPC'
KPL/PCK

   Radii for the observatory "bodies" defined in observatories.bsp /
   observatories.tf, so that they can serve as the light source in
   edterm() when computing the radar terminator (the edge of the lunar
   region illuminated by the transmitter).

   These values are hand-maintained in this dedicated kernel because
   observatories.tf is generated by PINPOINT: regenerating it would
   silently drop any hand-added radii (a duplicate definition currently
   in observatories.tf is kept for older scripts; this kernel is loaded
   afterwards and takes precedence).

   The 20 m radius approximates the Dwingeloo (399999, 25 m dish),
   Stockert (399998, 25 m dish), and ATA (399997, Allen Telescope Array)
   stations. For terminator purposes the exact value is irrelevant: any
   small radius makes the umbral and penumbral terminators coincide with
   the radar limb.

\begindata

   BODY399999_RADII = ( 0.02   0.02   0.02 )
   BODY399998_RADII = ( 0.02   0.02   0.02 )
   BODY399997_RADII = ( 0.02   0.02   0.02 )

\begintext
TPC

echo "Regenerated $KDIR/observatories.{bsp,tf} and observatory_radii.tpc from observatories.defs"
